config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if ENV['MAILER_DELIVERY_METHOD'] != 'smtp'
  get '/login', to: 'frontend/sessions#new'
  post '/login', to: 'frontend/sessions#create'
  get '/register', to: 'frontend/users#new'
  post '/register', to: 'frontend/users#create'

  get '/logout', to: 'frontend/sessions#destroy'
  post '/logout', to: 'frontend/sessions#destroy'

  get 'download_game_windows', to: 'frontend/welcome#download_game_windows'
  get 'download_game_linux', to: 'frontend/welcome#download_game_linux'

  namespace :api do
    namespace :v1 do
      post '/auth/login', to: 'authentications#login'
      post '/auth/validate_token', to: 'authentications#validate_token'
      post '/token/revoke', to: 'jwt_blacklists#create'
      post '/game/upload', to: 'games#upload'

      get '/users/me', to: 'users#me'
    end
  end

  scope module: 'frontend', as: 'frontend' do
    root to: 'welcome#index'
    resources :users, only: %i[show edit update] do
      resources :scores, only: [:index] do
        resources :achievements, only: [:index]
      end
      member do
        get :confirm_email
        get :reset_password
        post :reset_password
      end
      get '/upload-image', to: 'users#upload_image'
      post '/upload-image', to: 'users#upload_image'
    end

    get '/reset_password', to: 'reset_passwords#new'
    post '/reset_password', to: 'reset_passwords#create_reset_password_link'

    resources :scores, only: %i[index show], path: '/leaderboards'
    resources :achievements, only: %i[index show]

    get '/gameinfo' => 'welcome#gameinfo'
    get '/help' => 'welcome#help'
    get '/leaderboard' => 'welcome#leaderboard'

    get '/imprint' => 'welcome#imprint'
    get '/privacy' => 'welcome#privacy'
    get '/legacy' => 'welcome#legacy'
    get '/updates' => 'welcome#updates'
    get '/user-agreement' => 'welcome#user_agreement'

    resources :sessions
    resources :news
  end

  scope module: 'backend', as: 'backend', path: 'admin' do
    root to: 'welcome#index'
    resources :users
    resources :news
    resources :characters
    resources :faqs
    resources :achievements
    resources :games
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  has_many :games, dependent: :destroy
  has_many :accomplished_achievements, through: :games, dependent: :destroy
  has_one_attached :avatar, dependent: :destroy

  before_create :confirmation_token, :downcase_email

  validates :username, presence: true, uniqueness: true, on: :create, length: { maximum: 16 }
  validate :validate_email
  validates :password, length: { minimum: 8 }, allow_nil: true
  validates :tos, presence: true

  enum role: { standard: 0, admin: 1 }

  def email_activate
    self.email_confirmed = true
    self.confirm_token   = nil
    save!(validate: false)
  end

  def generate_reset_password_token
    self.reset_password_token = SecureRandom.urlsafe_base64.to_s
    save!(validate: false)
  end

  private

  def validate_email
    return if email.present? && email =~ URI::MailTo::EMAIL_REGEXP

    if email.blank? && email != ~URI::MailTo::EMAIL_REGEXP
      errors.add(:email, :blank)
    elsif email.present? && email != ~URI::MailTo::EMAIL_REGEXP
      errors.add(:email, :invalid)
    end
  end

  def confirmation_token
    self.confirm_token = SecureRandom.urlsafe_base64.to_s
  end

  def downcase_email
    return if email.blank?

    email.downcase!
  end
end

app/controllers/api/v1/users_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class UsersController < Api::V1::ApiController
      def me
        render json: Current.user, status: :ok
      end

      private

      def user_params
        params.require(:user).permit(
          :username,
          :email,
          :password
        )
      end
    end
  end
end

app/controllers/backend/users_controller.rb
# frozen_string_literal: true

module Backend
  class UsersController < Backend::BackendController
    def index
      controller_authorize(User)

      @users = User.all.order('id DESC')
    end

    def show
      controller_authorize(user)
    end

    def new
      controller_authorize(User)

      @user = User.new
    end

    def edit
      controller_authorize(user)
    end

    def create
      controller_authorize(User)

      user = User.new(permitted_attributes(User))

      if user.save
        session[:user_id] = user.id
        redirect_to backend_users_path, flash: { success: t('.success') }
      else
        redirect_to new_backend_user_path, flash: { error: t('.failed') }
      end
    end

    def update
      controller_authorize(user)

      if @user.update(permitted_attributes(user))
        redirect_to edit_backend_user_path(user), flash: { success: t('.success') }
      else
        redirect_to edit_backend_user_path(user), flash: { error: t('.failed') }
      end
    end

    def destroy
      controller_authorize(user)

      if user.destroy
        redirect_to backend_users_path, flash: { success: t('.success') }
      else
        redirect_to backend_users_path, flash: { error: t('.failed') }
      end
    end

    private

    def user
      @user ||= User.find_by(id: params[:id])
    end
  end
end

app/controllers/frontend/achievements_controller.rb
# frozen_string_literal: true

module Frontend
  class AchievementsController < Frontend::FrontendController
    def index
      controller_authorize(Achievement)
      @achievements = Achievement.all
    end

    def show
      controller_authorize(achievement)
    end

    private

    def achievement
      @achievement ||= Achievement.find_by(id: params[:id])
    end
  end
end

app/controllers/frontend/frontend_controller.rb
# frozen_string_literal: true

module Frontend
  class FrontendController < ApplicationController
    layout 'frontend'

    def index; end
  end
end

app/controllers/frontend/news_controller.rb
# frozen_string_literal: true

module Frontend
  class NewsController < Frontend::FrontendController
    def index
      controller_authorize(News)

      @news = News.all
    end

    def show
      controller_authorize(news)

      @other_news = News.where.not(id: news).limit(3).order('RANDOM()')
    end

    private

    def news
      @news ||= News.find_by(id: params[:id])
    end
  end
end

app/controllers/frontend/reset_passwords_controller.rb
# frozen_string_literal: true

module Frontend
  class ResetPasswordsController < Frontend::FrontendController
    def new
      controller_authorize(User)
    end

    def create_reset_password_link
      controller_authorize(User)

      user = User.find_by(email: params[:email])

      if user
        user.generate_reset_password_token
        UserMailer.reset_password_link(user).deliver!
      end

      respond_to do |format|
        format.html { render 'frontend/reset_passwords/successful' }
      end
    end
  end
end

app/controllers/frontend/sessions_controller.rb
# frozen_string_literal: true

module Frontend
  class SessionsController < Frontend::FrontendController
    def new
      controller_authorize(User)
    end

    def create
      controller_authorize(User)

      @user = User.find_by('lower(email) = ?', params[:email].downcase)
      if @user&.authenticate(params[:password])
        if @user.email_confirmed
          if params[:remember_me].to_i == 1
            cookies.permanent[:auth_token] = @user.id
          else
            session[:user_id] = @user.id
          end

          redirect_to frontend_user_path(@user), flash: { success: t('.success') }
        else
          UserMailer.registration_confirmation(@user).deliver!
          redirect_to login_path, flash: { error: t('.confirm_email') }
        end
      else
        redirect_to login_path, flash: { error: t('.failed') }
      end
    end

    def destroy
      controller_authorize(User)

      cookies[:auth_token] = nil
      session[:user_id]    = nil
      redirect_to frontend_root_path
    end
  end
end

app/controllers/frontend/users_controller.rb
# frozen_string_literal: true

module Frontend
  class UsersController < Frontend::FrontendController
    def show
      controller_authorize(user)
    end

    def new
      controller_authorize(User)
      @user = User.new
    end

    def edit
      controller_authorize(user)
    end

    def create
      controller_authorize(User)

      user = User.new(permitted_attributes(User))
      user.avatar.attach(params[:user][:avatar])

      if user.save
        UserMailer.registration_confirmation(user).deliver!
        redirect_to login_path, flash: { success: t('.success') }
      else
        flash[:error] ||= []

        user.errors.each do |error|
          flash[:error] << error.message
        end

        redirect_to register_path
      end
    end

    def update
      controller_authorize(user)

      if user.update(permitted_attributes(user))
        token = JsonWebToken.encode(user_id: user.id, email: user.email, password: user.password)
        user.update_attribute(:token, token)
        redirect_to frontend_user_path(user), flash: { success: t('.success') }
      else
        redirect_to edit_frontend_user_path(user), flash: { error: t('.failed') }
      end
    end

    def destroy
      controller_authorize(user)

      user.destroy

      redirect_to frontend_root_path
    end

    def confirm_email
      controller_authorize(User.find_by(confirm_token: params[:id]))

      user = User.find_by(confirm_token: params[:id])
      if user
        user.email_activate
        redirect_to login_path, flash: { success: t('.success') } # Render special view for activation page
      else
        redirect_to frontend_root_path, flash: { error: t('.failed') }
      end
    end

    def reset_password
      controller_authorize(User.find_by(reset_password_token: params[:id]))

      @user = User.find_by(reset_password_token: params[:id])

      return unless request.post?

      if user.update(permitted_attributes(user))
        user.update_attribute(:reset_password_token, nil)
        redirect_to login_path, flash: { success: t('.success') }
      else
        redirect_to reset_password_frontend_user_path, flash: { error: t('.failed') }
        # Das Passwort konnte leider nicht zurückgesetzt werden,
        # bitte sende eine E-Mail an: support@freezetogether.com
      end
    end

    def upload_image
      controller_authorize(User.find_by(id: params[:user_id]))

      user  = User.find_by(id: params[:user_id])
      image = params[:user][:avatar]
      user.avatar.attach(image)
      redirect_to frontend_user_path(user)
    end

    private

    def user
      @user ||= User.find_by(id: params[:id])
    end
  end
end

app/controllers/frontend/welcome_controller.rb
# frozen_string_literal: true

module Frontend
  class WelcomeController < Frontend::FrontendController
    def index
      controller_authorize(User)

      @news = News.last(3)
    end

    def gameinfo
      controller_authorize(User)
    end

    def imprint
      controller_authorize(User)
    end

    def legacy
      controller_authorize(User)
    end

    def updates
      controller_authorize(User)
    end

    def user_agreement
      controller_authorize(User)
    end

    def privacy
      controller_authorize(User)
    end

    def download_game_windows
      controller_authorize(User)
      send_file Rails.root.join('app/assets/download/FreezeTogetherWin.zip'), type: 'application/zip', x_sendfile: true
    end

    def download_game_linux
      controller_authorize(User)
      send_file Rails.root.join('app/assets/download/FreezeTogetherLinux.zip'), type: 'application/zip', x_sendfile: true
    end

    def help
      controller_authorize(User)
    end

    def leaderboard
      controller_authorize(User)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < BackendController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :permission, only: [:show]
  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to @user, notice: "Successfully registered!"
      else
        redirect_to register_path, notice: "Registration failed!"
      end

  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
    def permission
      if current_user != set_user
        redirect_to users_path, notice: "No Permission!"
      end
    end
    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(
        :username,
        :email,
        :password
      )
    end
end

app/helpers/frontend_helper.rb
# frozen_string_literal: true

module FrontendHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def user_avatar(user, size = 400)
    if user.avatar.attached?
      user.avatar.variant(resize: "#{size}x#{size}!")
    else
      'https://randomuser.me/api/portraits/women/49.jpg'
    end
  end
end

app/views/frontend/users/_form.html.haml
%section
  .container
    .login-register
      .head-text.text-center
        %h2.head-text__headline Registration
        %p.head-text__description Bist du bereit auf ein Abenteuer?
      = form_for @user, url: register_path, class: 'login-form' do |f|
        = f.text_field :email, placeholder: 'E-Mail-Adresse'
        = f.text_field :username, placeholder: 'Benutzername'
        = f.password_field :password, placeholder: 'Passwort'
        .form-sub
          = f.label :tos, class: 'checkbox' do
            = f.check_box :tos
            .checkmark
            .description
              Ich habe die
              = link_to 'Nutzungsbedingungen', frontend_user_agreement_path, target: '_blank'
              gelesen und akzeptiere sie.
        = f.submit "Kostenlos registrieren", class: 'button button--accent'
      .login-register__caption
        Bereits registriert?
        = link_to "Jetzt einloggen!", login_path

app/views/frontend/users/edit.html.haml
%section
  .container
    .login-register
      .head-text.text-center
        %h2.head-text__headline Benutzer bearbeiten
      = form_for [:frontend, @user], class: 'login-form' do |f|
        = f.text_field :email, placeholder: 'E-Mail-Adresse'
        = f.text_field :description, placeholder: 'Profilbeschreibung'
        = f.password_field :password, placeholder: 'Passwort'
        = f.submit "Abspeichern", class: 'button button--accent'

app/views/frontend/users/new.html.erb
<%= render 'form' %>

app/views/frontend/users/reset_password.html.haml
%section
  .container
    .login-register
      .head-text.text-center
        %h2.head-text__headline Passwort zurücksetzen
        %p.head-text__description Bist du bereit auf ein Abenteuer?
      = form_for @user, url: reset_password_frontend_user_path, method: :post, class: 'login-form' do |f|
        = f.password_field :password, placeholder: 'Passwort', class: 'mb-1'
        = f.submit "Passwört ändern", class: 'button button--accent button--w-full'

app/views/frontend/users/show.html.haml
.profile
  .profile__banner
    .profile-banner
      = image_tag (@user&.avatar&.attached? ? @user&.avatar : "default.png")
    - if policy([:frontend, @user]).edit?
      .user-gear
        = link_to image_tag("icons/gear-solid.svg", class: 'user-settings__image'), edit_frontend_user_path(@user), class: 'user-settings'
    .profile-transparent-hr
    .profile-data
      .profile-data__avatar
        .profile-avatar
          = image_tag (@user&.avatar&.attached? ? @user&.avatar : "default.png")
          - if policy([:frontend, @user]).upload_image?
            = form_for [:frontend, @user], url: frontend_user_upload_image_path(@user), method: :post do |f|
              = f.file_field :avatar
              .avatar-upload= "Avatar<br>ändern".html_safe
        .profile-avatar-outline
        .profile-avatar-status

      .profile-data__details
        .profile-details
          %h1.profile-details__username= @user.username
          .profile-details__description= @user.description
          %date.profile-details__date= @user.created_at.strftime("Registriert seit %d. %b. %Y")
.container
  .tabs
    %ul.tabs__list{role: "tablist"}
      %li.tabs__item{role: "presentation"}
        = link_to "Erfolge", "#erfolge", {class: 'tabs__link', "aria-controls": "erfolge", "aria-selected": "true", role: "tab", tabindex: "0"}
      %li.tabs__item{role:  "presentation"}
        = link_to "Spielverlauf", "#", {class: 'tabs__link', "aria-controls": "spielverlauf", "aria-selected": "false", href: "#spielverlauf", role: "tab", tabindex: "-1"}
    %section#erfolge.tabs__section{"aria-hidden": "false", "aria-labelledby": "tab-erfolge", role: "tabpanel"}
      .tabs__body
        .achievements
          - @user.accomplished_achievements.uniq(&:achievement).each do |achievement|
            = render 'frontend/users/tabs/achievement-card', achievement: achievement
    %section#spielverlauf.tabs__section{"aria-hidden": "true", "aria-labelledby": "tab-spielverlauf", role: "tabpanel"}
      .tabs__body
        .games
          .games__item.games__item--header
            %div Datum
            %div Punkte
            %div Coins
            %div Erfolge
            %div Zeit
          - @user.games.order(time: :asc, score: :desc, coin: :desc, created_at: :asc).limit(10).each do |game|
            = render 'frontend/users/tabs/game-card', game: game