config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if ENV['MAILER_DELIVERY_METHOD'] != 'smtp'
  get '/login', to: 'frontend/sessions#new'
  post '/login', to: 'frontend/sessions#create'
  get '/register', to: 'frontend/users#new'
  post '/register', to: 'frontend/users#create'

  get '/logout', to: 'frontend/sessions#destroy'
  post '/logout', to: 'frontend/sessions#destroy'

  get 'download_game_windows', to: 'frontend/welcome#download_game_windows'
  get 'download_game_linux', to: 'frontend/welcome#download_game_linux'

  namespace :api do
    namespace :v1 do
      post '/auth/login', to: 'authentications#login'
      post '/auth/validate_token', to: 'authentications#validate_token'
      post '/token/revoke', to: 'jwt_blacklists#create'
      post '/game/upload', to: 'games#upload'

      get '/users/me', to: 'users#me'
    end
  end

  scope module: 'frontend', as: 'frontend' do
    root to: 'welcome#index'
    resources :users, only: %i[show edit update] do
      resources :scores, only: [:index] do
        resources :achievements, only: [:index]
      end
      member do
        get :confirm_email
        get :reset_password
        post :reset_password
      end
      get '/upload-image', to: 'users#upload_image'
      post '/upload-image', to: 'users#upload_image'
    end

    get '/reset_password', to: 'reset_passwords#new'
    post '/reset_password', to: 'reset_passwords#create_reset_password_link'

    resources :scores, only: %i[index show], path: '/leaderboards'
    resources :achievements, only: %i[index show]

    get '/gameinfo' => 'welcome#gameinfo'
    get '/help' => 'welcome#help'
    get '/leaderboard' => 'welcome#leaderboard'

    get '/imprint' => 'welcome#imprint'
    get '/privacy' => 'welcome#privacy'
    get '/legacy' => 'welcome#legacy'
    get '/updates' => 'welcome#updates'
    get '/user-agreement' => 'welcome#user_agreement'

    resources :sessions
    resources :news
  end

  scope module: 'backend', as: 'backend', path: 'admin' do
    root to: 'welcome#index'
    resources :users
    resources :news
    resources :characters
    resources :faqs
    resources :achievements
    resources :games
  end
end

app/controllers/frontend/achievements_controller.rb
# frozen_string_literal: true

module Frontend
  class AchievementsController < Frontend::FrontendController
    def index
      controller_authorize(Achievement)
      @achievements = Achievement.all
    end

    def show
      controller_authorize(achievement)
    end

    private

    def achievement
      @achievement ||= Achievement.find_by(id: params[:id])
    end
  end
end

app/controllers/frontend/frontend_controller.rb
# frozen_string_literal: true

module Frontend
  class FrontendController < ApplicationController
    layout 'frontend'

    def index; end
  end
end

app/controllers/frontend/news_controller.rb
# frozen_string_literal: true

module Frontend
  class NewsController < Frontend::FrontendController
    def index
      controller_authorize(News)

      @news = News.all
    end

    def show
      controller_authorize(news)

      @other_news = News.where.not(id: news).limit(3).order('RANDOM()')
    end

    private

    def news
      @news ||= News.find_by(id: params[:id])
    end
  end
end

app/controllers/frontend/reset_passwords_controller.rb
# frozen_string_literal: true

module Frontend
  class ResetPasswordsController < Frontend::FrontendController
    def new
      controller_authorize(User)
    end

    def create_reset_password_link
      controller_authorize(User)

      user = User.find_by(email: params[:email])

      if user
        user.generate_reset_password_token
        UserMailer.reset_password_link(user).deliver!
      end

      respond_to do |format|
        format.html { render 'frontend/reset_passwords/successful' }
      end
    end
  end
end

app/controllers/frontend/sessions_controller.rb
# frozen_string_literal: true

module Frontend
  class SessionsController < Frontend::FrontendController
    def new
      controller_authorize(User)
    end

    def create
      controller_authorize(User)

      @user = User.find_by('lower(email) = ?', params[:email].downcase)
      if @user&.authenticate(params[:password])
        if @user.email_confirmed
          if params[:remember_me].to_i == 1
            cookies.permanent[:auth_token] = @user.id
          else
            session[:user_id] = @user.id
          end

          redirect_to frontend_user_path(@user), flash: { success: t('.success') }
        else
          UserMailer.registration_confirmation(@user).deliver!
          redirect_to login_path, flash: { error: t('.confirm_email') }
        end
      else
        redirect_to login_path, flash: { error: t('.failed') }
      end
    end

    def destroy
      controller_authorize(User)

      cookies[:auth_token] = nil
      session[:user_id]    = nil
      redirect_to frontend_root_path
    end
  end
end

app/controllers/frontend/users_controller.rb
# frozen_string_literal: true

module Frontend
  class UsersController < Frontend::FrontendController
    def show
      controller_authorize(user)
    end

    def new
      controller_authorize(User)
      @user = User.new
    end

    def edit
      controller_authorize(user)
    end

    def create
      controller_authorize(User)

      user = User.new(permitted_attributes(User))
      user.avatar.attach(params[:user][:avatar])

      if user.save
        UserMailer.registration_confirmation(user).deliver!
        redirect_to login_path, flash: { success: t('.success') }
      else
        flash[:error] ||= []

        user.errors.each do |error|
          flash[:error] << error.message
        end

        redirect_to register_path
      end
    end

    def update
      controller_authorize(user)

      if user.update(permitted_attributes(user))
        token = JsonWebToken.encode(user_id: user.id, email: user.email, password: user.password)
        user.update_attribute(:token, token)
        redirect_to frontend_user_path(user), flash: { success: t('.success') }
      else
        redirect_to edit_frontend_user_path(user), flash: { error: t('.failed') }
      end
    end

    def destroy
      controller_authorize(user)

      user.destroy

      redirect_to frontend_root_path
    end

    def confirm_email
      controller_authorize(User.find_by(confirm_token: params[:id]))

      user = User.find_by(confirm_token: params[:id])
      if user
        user.email_activate
        redirect_to login_path, flash: { success: t('.success') } # Render special view for activation page
      else
        redirect_to frontend_root_path, flash: { error: t('.failed') }
      end
    end

    def reset_password
      controller_authorize(User.find_by(reset_password_token: params[:id]))

      @user = User.find_by(reset_password_token: params[:id])

      return unless request.post?

      if user.update(permitted_attributes(user))
        user.update_attribute(:reset_password_token, nil)
        redirect_to login_path, flash: { success: t('.success') }
      else
        redirect_to reset_password_frontend_user_path, flash: { error: t('.failed') }
        # Das Passwort konnte leider nicht zurückgesetzt werden,
        # bitte sende eine E-Mail an: support@freezetogether.com
      end
    end

    def upload_image
      controller_authorize(User.find_by(id: params[:user_id]))

      user  = User.find_by(id: params[:user_id])
      image = params[:user][:avatar]
      user.avatar.attach(image)
      redirect_to frontend_user_path(user)
    end

    private

    def user
      @user ||= User.find_by(id: params[:id])
    end
  end
end

app/controllers/frontend/welcome_controller.rb
# frozen_string_literal: true

module Frontend
  class WelcomeController < Frontend::FrontendController
    def index
      controller_authorize(User)

      @news = News.last(3)
    end

    def gameinfo
      controller_authorize(User)
    end

    def imprint
      controller_authorize(User)
    end

    def legacy
      controller_authorize(User)
    end

    def updates
      controller_authorize(User)
    end

    def user_agreement
      controller_authorize(User)
    end

    def privacy
      controller_authorize(User)
    end

    def download_game_windows
      controller_authorize(User)
      send_file Rails.root.join('app/assets/download/FreezeTogetherWin.zip'), type: 'application/zip', x_sendfile: true
    end

    def download_game_linux
      controller_authorize(User)
      send_file Rails.root.join('app/assets/download/FreezeTogetherLinux.zip'), type: 'application/zip', x_sendfile: true
    end

    def help
      controller_authorize(User)
    end

    def leaderboard
      controller_authorize(User)
    end
  end
end

app/helpers/frontend_helper.rb
# frozen_string_literal: true

module FrontendHelper
end

app/views/layouts/frontend/_flash.html.haml
- flash.each do |type, messages|
  .flash{ class: "flash #{flash_classes(type)}" }
    - if messages.kind_of?(Array)
      - messages&.each do |message|
        %p.flash__message
          = message
    - else
      %p.flash__message
        = messages

app/views/layouts/frontend/_footer.html.haml
%footer.footer
  .footer__top
    .footer-weblinks
      %h3 Freeze Links
      %ul.weblinks
        %li.weblinks__item= link_to t('layouts.frontend.header.gameinfo'), frontend_gameinfo_path
        %li.weblinks__item= link_to t('layouts.frontend.header.news'), frontend_news_index_path
        %li.weblinks__item= link_to t('layouts.frontend.header.leaderboard'), frontend_leaderboard_path
        %li.weblinks__item= link_to t('layouts.frontend.header.help'), frontend_help_path
        %li.weblinks__item= link_to t('layouts.frontend.header.login'), login_path
    .footer-sm
      %ul.social-media-list
        %li.social-media-list__item= link_to image_tag('/assets/icons/instagram.svg'), '#'
        %li.social-media-list__item= link_to image_tag('/assets/icons/twitter.svg'), '#'
        %li.social-media-list__item= link_to image_tag('/assets/icons/discord.svg'), '#'
  .footer__bottom
    .footer-container
      .footer-container__logo
        = link_to (image_tag('/assets/logos/logo.svg')), frontend_root_path
      .footer-container__copyright
        .footer-copyright
          .footer-copyright__links
            %ul.copyright-links
              %li.copyright-links__item= link_to t('frontend.footer.impressum'), frontend_imprint_path
              %li.copyright-links__item= link_to t('frontend.footer.legal'), frontend_legacy_path
              %li.copyright-links__item= link_to t('frontend.footer.updates'), frontend_updates_path
              %li.copyright-links__item= link_to t('frontend.footer.user_agreement'), frontend_user_agreement_path
              %li.copyright-links__item= link_to t('frontend.footer.policies'), frontend_privacy_path
          .footer-copyright__text Copyright &copy; 2022 - Freeze Together.
    .footer-images
      = image_tag('/assets/icons/usk12.png', height: 75 )

app/views/layouts/frontend/_header.html.haml
%header.main-header
  %nav.main-nav
    .main-nav__navigation
      = link_to (image_tag('/assets/logos/logo-text.svg')), frontend_root_path, class: 'main-nav__logo'
      %ul.nav-list
        %li.nav-list__item.nav-list__item--selected= link_to t('.gameinfo'), frontend_gameinfo_path
        %li.nav-list__item= link_to t('.news'), frontend_news_index_path
        %li.nav-list__item= link_to t('.leaderboard'), frontend_leaderboard_path
        %li.nav-list__item= link_to t('.help'), frontend_help_path
    .main-nav__buttons
      - unless logged_in?
        = link_to "#{image_tag('/assets/icons/login.png')} #{t('.login')}".html_safe, login_path, class: 'button button--login'
      - else
        = link_to t('.logout').html_safe, logout_path, class: 'button button--login'
        = link_to (image_tag(Current.user&.avatar&.attached? ? Current.user&.avatar : "default.png")), frontend_user_url(Current.user), class: 'button button--avatar mr-2'