config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if ENV['MAILER_DELIVERY_METHOD'] != 'smtp'
  get '/login', to: 'frontend/sessions#new'
  post '/login', to: 'frontend/sessions#create'
  get '/register', to: 'frontend/users#new'
  post '/register', to: 'frontend/users#create'

  get '/logout', to: 'frontend/sessions#destroy'
  post '/logout', to: 'frontend/sessions#destroy'

  get 'download_game_windows', to: 'frontend/welcome#download_game_windows'
  get 'download_game_linux', to: 'frontend/welcome#download_game_linux'

  namespace :api do
    namespace :v1 do
      post '/auth/login', to: 'authentications#login'
      post '/auth/validate_token', to: 'authentications#validate_token'
      post '/token/revoke', to: 'jwt_blacklists#create'
      post '/game/upload', to: 'games#upload'

      get '/users/me', to: 'users#me'
    end
  end

  scope module: 'frontend', as: 'frontend' do
    root to: 'welcome#index'
    resources :users, only: %i[show edit update] do
      resources :scores, only: [:index] do
        resources :achievements, only: [:index]
      end
      member do
        get :confirm_email
        get :reset_password
        post :reset_password
      end
      get '/upload-image', to: 'users#upload_image'
      post '/upload-image', to: 'users#upload_image'
    end

    get '/reset_password', to: 'reset_passwords#new'
    post '/reset_password', to: 'reset_passwords#create_reset_password_link'

    resources :scores, only: %i[index show], path: '/leaderboards'
    resources :achievements, only: %i[index show]

    get '/gameinfo' => 'welcome#gameinfo'
    get '/help' => 'welcome#help'
    get '/leaderboard' => 'welcome#leaderboard'

    get '/imprint' => 'welcome#imprint'
    get '/privacy' => 'welcome#privacy'
    get '/legacy' => 'welcome#legacy'
    get '/updates' => 'welcome#updates'
    get '/user-agreement' => 'welcome#user_agreement'

    resources :sessions
    resources :news
  end

  scope module: 'backend', as: 'backend', path: 'admin' do
    root to: 'welcome#index'
    resources :users
    resources :news
    resources :characters
    resources :faqs
    resources :achievements
    resources :games
  end
end

app/models/character.rb
# frozen_string_literal: true

class Character < ApplicationRecord
  validates :title, presence: true
  validates :name, presence: true
  validates :description, presence: true
  validates :quote, presence: true
  # validates :image, attached: true, content_type: ['image/png', 'image/jpeg', 'image/svg'] ## BUGFIX!

  has_rich_text :description
  has_rich_text :quote
  has_one_attached :image
end

app/controllers/backend/achievements_controller.rb
# frozen_string_literal: true

module Backend
  class AchievementsController < Backend::BackendController
    def index
      controller_authorize(Achievement)

      @achievements = Achievement.all.order('id DESC')
    end

    def show
      controller_authorize(achievement)
    end

    def new
      controller_authorize(Achievement)

      @achievement = Achievement.new
    end

    def edit
      controller_authorize(achievement)
    end

    def create
      controller_authorize(Achievement)

      achievement = Achievement.new(permitted_attributes(Achievement))
      achievement.cover_image.attach(params[:achievement][:cover_image])

      if achievement.save
        redirect_to backend_achievements_path, flash: { success: t('.success') }
      else
        redirect_to new_backend_achievement_path, flash: { error: t('.failed') }
      end
    end

    def update
      controller_authorize(achievement)

      achievement.cover_image.attach(params[:achievement][:cover_image]) if params[:achievement][:cover_image]

      if achievement.update(permitted_attributes(achievement))
        redirect_to edit_backend_achievement_path(achievement), flash: { success: t('.success') }
      else
        redirect_to edit_backend_achievement_path(achievement), flash: { error: t('.failed') }
      end
    end

    def destroy
      controller_authorize(achievement)
      if achievement.destroy
        redirect_to backend_achievements_path, flash: { success: t('.success') }
      else
        redirect_to backend_achievements_path, flash: { error: t('.failed') }
      end
    end

    private

    def achievement
      @achievement ||= Achievement.find_by(id: params[:id])
    end
  end
end

app/controllers/backend/backend_controller.rb
# frozen_string_literal: true

module Backend
  class BackendController < ApplicationController
    layout 'backend'
  end
end

app/controllers/backend/characters_controller.rb
# frozen_string_literal: true

module Backend
  class CharactersController < Backend::BackendController
    def index
      controller_authorize(Character)

      @characters = Character.all.order('id DESC')
    end

    def show
      controller_authorize(character)
    end

    def new
      controller_authorize(Character)

      @character = Character.new
    end

    def edit
      controller_authorize(character)
    end

    def create
      controller_authorize(Character)

      character = Character.new(permitted_attributes(Character))
      character.image.attach(params[:character][:image])

      if character.save
        redirect_to backend_characters_path, flash: { success: t('.success') }
      else
        redirect_to new_backend_character_path, flash: { error: t('.failed') }
      end
    end

    def update
      controller_authorize(character)

      character.image.attach(params[:character][:image]) if params[:character][:image]

      if character.update(permitted_attributes(character))
        redirect_to edit_backend_character_path(character), flash: { success: t('.success') }
      else
        redirect_to edit_backend_character_path(character), flash: { error: t('.failed') }
      end
    end

    def destroy
      controller_authorize(character)
      if character.destroy
        redirect_to backend_characters_path, flash: { success: t('.success') }
      else
        redirect_to backend_characters_path, flash: { error: t('.failed') }
      end
    end

    private

    def character
      @character ||= Character.find_by(id: params[:id])
    end
  end
end

app/controllers/backend/faqs_controller.rb
# frozen_string_literal: true

module Backend
  class FaqsController < Backend::BackendController
    def index
      controller_authorize(Faq)

      @faqs = Faq.all.order('id DESC')
    end

    def show
      controller_authorize(faq)
    end

    def new
      controller_authorize(Faq)

      @faq = Faq.new
    end

    def edit
      controller_authorize(faq)
    end

    def create
      controller_authorize(Faq)

      faq = Faq.new(permitted_attributes(Faq))

      if faq.save
        redirect_to backend_faqs_path, flash: { success: t('.success') }
      else
        redirect_to new_backend_faq_path, flash: { error: t('.failed') }
      end
    end

    def update
      controller_authorize(faq)

      if @faq.update(permitted_attributes(faq))
        redirect_to edit_backend_faq_path(faq), flash: { success: t('.success') }
      else
        redirect_to edit_backend_faq_path(faq), flash: { error: t('.failed') }
      end
    end

    def destroy
      controller_authorize(faq)
      if faq.destroy
        redirect_to backend_faqs_path, flash: { success: t('.success') }
      else
        redirect_to backend_faqs_path, flash: { error: t('.failed') }
      end
    end

    private

    def faq
      @faq ||= Faq.find_by(id: params[:id])
    end
  end
end

app/controllers/backend/games_controller.rb
# frozen_string_literal: true

module Backend
  class GamesController < Backend::BackendController
    def index
      controller_authorize(Game)

      @games = Game.all.order('id DESC')
    end

    def show
      controller_authorize(game)
    end

    def new
      controller_authorize(Game)

      @game = Game.new
    end

    def edit
      controller_authorize(game)
    end

    def create
      controller_authorize(Game)

      game = Game.new(permitted_attributes(Game))
      game.cover_image.attach(params[:game][:cover_image])

      if game.save
        redirect_to backend_games_path, flash: { success: t('.success') }
      else
        redirect_to new_backend_game_path, flash: { error: t('.failed') }
      end
    end

    def update
      controller_authorize(game)

      game.avatar.attach(params[:game][:cover_image]) if params[:game][:cover_image]

      if game.update(permitted_attributes(game))
        redirect_to edit_backend_game_path(game), flash: { success: t('.success') }
      else
        redirect_to edit_backend_game_path(game), flash: { error: t('.failed') }
      end
    end

    def destroy
      controller_authorize(game)
      if game.destroy
        redirect_to backend_games_path, flash: { success: t('.success') }
      else
        redirect_to backend_games_path, flash: { error: t('.failed') }
      end
    end

    private

    def game
      @game ||= Game.find_by(id: params[:id])
    end
  end
end

app/controllers/backend/news_controller.rb
# frozen_string_literal: true

module Backend
  class NewsController < Backend::BackendController
    def index
      controller_authorize(News)

      @news = News.all.order('id DESC')
    end

    def show
      controller_authorize(News)
    end

    def new
      controller_authorize(News)

      @news = News.new
    end

    def edit
      controller_authorize(news)
    end

    def create
      controller_authorize(News)

      news = News.new(permitted_attributes(News))

      if news.save
        news.cover_image.attach(params[:news][:cover_image])
        redirect_to backend_news_index_path, flash: { success: t('.success') }
      else
        redirect_to new_backend_news_path, flash: { error: t('.failed') }
      end
    end

    def update
      controller_authorize(news)

      if news.update(permitted_attributes(news))
        redirect_to edit_backend_news_path(news), flash: { success: t('.success') }
      else
        redirect_to edit_backend_news_path(news), flash: { error: t('.failed') }
      end
    end

    def destroy
      controller_authorize(news)

      if news.destroy
        redirect_to backend_news_index_path, flash: { success: t('.success') }
      else
        redirect_to backend_news_index_path, flash: { error: t('.error') }
      end
    end

    private

    def news
      @news ||= News.find_by(id: params[:id])
    end
  end
end

app/controllers/backend/users_controller.rb
# frozen_string_literal: true

module Backend
  class UsersController < Backend::BackendController
    def index
      controller_authorize(User)

      @users = User.all.order('id DESC')
    end

    def show
      controller_authorize(user)
    end

    def new
      controller_authorize(User)

      @user = User.new
    end

    def edit
      controller_authorize(user)
    end

    def create
      controller_authorize(User)

      user = User.new(permitted_attributes(User))

      if user.save
        session[:user_id] = user.id
        redirect_to backend_users_path, flash: { success: t('.success') }
      else
        redirect_to new_backend_user_path, flash: { error: t('.failed') }
      end
    end

    def update
      controller_authorize(user)

      if @user.update(permitted_attributes(user))
        redirect_to edit_backend_user_path(user), flash: { success: t('.success') }
      else
        redirect_to edit_backend_user_path(user), flash: { error: t('.failed') }
      end
    end

    def destroy
      controller_authorize(user)

      if user.destroy
        redirect_to backend_users_path, flash: { success: t('.success') }
      else
        redirect_to backend_users_path, flash: { error: t('.failed') }
      end
    end

    private

    def user
      @user ||= User.find_by(id: params[:id])
    end
  end
end

app/controllers/backend/welcome_controller.rb
# frozen_string_literal: true

module Backend
  class WelcomeController < Backend::BackendController
    def index
      controller_authorize(User)
    end
  end
end

app/helpers/backend_helper.rb
# frozen_string_literal: true

module BackendHelper
  def active_link_to(name = nil, options = nil, html_options = nil, &block)
    active_class         = html_options[:active] || 'active'
    html_options.delete(:active)
    if current_page?(options) || (request.path =~ (/#{options}/) && !html_options[:disable_affinity])
      html_options[:class] =
        "#{html_options[:class]} #{active_class}"
    end
    link_to(name, options, html_options, &block)
  end
end

app/views/backend/characters/_form.html.haml
= form_for [:backend, @character] do |f|
  .form__item
    %h4.heading= "#{controller.action_name} #{@character.class.name}"
  .form__item
    = f.label :image
    = (image_tag (@character&.image), height: 100) if @character&.image&.attached?
    = f.file_field :image
  .form__item
    = f.label :name
    = f.text_field :name
  .form__item
    = f.label :title
    = f.text_field :title
  .form__item
    = f.label :description
    %div= f.rich_text_area :description
  .form__item
    = f.label :quote
    %div= f.rich_text_area :quote
  .form__buttons
    - if controller.action_name == 'edit'
      = f.submit 'Update'
    - else
      = f.submit 'Create'

app/views/backend/characters/edit.html.haml
= link_to "Back to Characters", backend_characters_path, class: 'backto'
.edit
  .form
    .form__content
      = render 'form', character: @character

app/views/backend/characters/index.html.haml
.navigation-buttons
  = link_to "Add Character", new_backend_character_path, class: 'button'
.table
  .table__head
    .tc ID
    .tc image
    .tc title
    .tc charactername
    .tc.center Edit
    .tc.center Delete
  - @characters.each do |character|
    .table__item
      .tc.show
        = link_to edit_backend_character_path(character) do
          = character.id
      .tc.show
        = link_to edit_backend_character_path(character) do
          = (image_tag (character&.image), height: 100) if character&.image&.attached?
      .tc= character.title
      .tc.show
        = link_to edit_backend_character_path(character) do
          = character.name
      .tc.center.edit
        = link_to edit_backend_character_path(character) do
          %svg{"enable-background" => "new 0 0 220.001 220.001", :space => "preserve", :version => "1.1", :viewbox => "0 0 220 220", :xmlns => "http://www.w3.org/2000/svg"}
            %polygon{:points => "0 220 59.34 213.86 6.143 160.66"}
            %path{:d => "m132.02 34.787 53.197 53.197-115.65 115.65-53.198-53.197 115.65-115.65zm80.678 25.715c9.738-9.738 9.742-25.527 0-35.268l-17.93-17.93c-9.738-9.74-25.529-9.738-35.268 0l-17.346 17.347 53.199 53.196 17.345-17.345z"}
      .tc.center.delete
        = button_to backend_character_path(character), method: :delete do
          %svg{"enable-background" => "new 0 0 512 512", :space => "preserve", :version => "1.1", :viewbox => "0 0 512 512", :xmlns => "http://www.w3.org/2000/svg"}
            %path{:d => "m432 96h-48v-64c0-17.672-14.328-32-32-32h-192c-17.672 0-32 14.328-32 32v64h-48c-17.672 0-32 14.328-32 32v32h416v-32c0-17.672-14.328-32-32-32zm-240 0v-32h128v32h-128z"}
            %path{:d => "m80 480c0 17.672 14.324 31.996 31.996 31.996h288.01c17.668 0 31.992-14.324 31.992-31.992v-288.01h-352v288zm240-208c0-8.836 7.164-16 16-16s16 7.164 16 16v160c0 8.836-7.164 16-16 16s-16-7.164-16-16v-160zm-80 0c0-8.836 7.164-16 16-16s16 7.164 16 16v160c0 8.836-7.164 16-16 16s-16-7.164-16-16v-160zm-80 0c0-8.836 7.164-16 16-16s16 7.164 16 16v160c0 8.836-7.164 16-16 16s-16-7.164-16-16v-160z"}

app/views/backend/characters/new.html.haml
= link_to "Back to Characters", backend_characters_path, class: 'backto'
.edit
  .form
    .form__content
      = render 'form', character: @character